# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hangsesh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Hangsesh
  pod 'lottie-ios'
  
  target 'HangseshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HangseshUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
